language: php

sudo: false

matrix:
  include:
  - name: PHP 5.6
    php: 5.6
  - name: PHP 7.1
    php: 7.1
    env: WITH_ALLURE=1
  - name: PHP 7.1
    php: 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  # Avoid memory issues on composer install
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update

install:
  - composer install
  - if [ "${WITH_ALLURE}" == "1" ] ; then composer require "ezsystems/allure-behat:^2.0" ; fi
  - docker run -p 4444:4444 --shm-size=256m -d selenium/standalone-chrome-debug:3.4.0

script:
  - bin/phpspec run --no-interaction --format=pretty
  - bin/behat --no-interaction --format=pretty -vv
  - ./bin/php-cs-fixer fix --dry-run
