language: php

sudo: false

matrix:
  include:
  - name: PHP 5.6
    php: 5.6
  - name: PHP 7.1
    php: 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer install
  - docker run -p 4444:4444 --shm-size=256m -d selenium/standalone-chrome-debug:3.4.0

script:
  - bin/phpspec run --no-interaction --format=pretty
  - bin/behat --no-interaction --format=pretty -vv
  - ./bin/php-cs-fixer fix --dry-run
